name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.0
  http: ^1.6.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  jiffy: ^6.4.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/SplashScreenStick.png
   - assets/images/logincontainer.png
   - assets/images/Avatar.png