name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/SplashScreenStick.png
   - assets/images/logincontainer.png